export { default as Home } from './Home'
export { default as Shop } from './Shop'
export { default as Bio } from './Bio'
export { default as Contact } from './Contact'
export { default as Gallery } from './Gallery'
